var TEXT_GAMEOVER  = "GAME OVER";
var TEXT_PLAY      = "PLAY";
var TEXT_RESTART   = "RESTART";
var TEXT_TIME      = "TIME";
var TEXT_SCORE     = "SCORE"; 
var TEXT_LEVELEND = "LEVEL %s COMPLETE";

var TEXT_SPLAT = "SPLAT!";
var TEXT_DROWN = "GLU GLU..";
var TEXT_CRASH = "BONK!";
var TEXT_GREAT = "GREAT!!";

var TEXT_HELP1     = "USE ARROWS KEYS TO REACH THE OTHER SIDE OF THE RIVER BEFORE TIME RUNS OUT. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";
var TEXT_HELP2     = "DON'T GET DRIVEN OVER BY CARS ALONG THE STREET";
var TEXT_HELP3     = "USE THE FLOATING TRUNKS OR TURTLE SHELLS TO CROSS THE RIVER";
var TEXT_HELP4     = "IF YOU CATCH A FLY, YOU GET EXTRA POINTS";

var TEXT_HELP_MOB1 = "SWIPE TO REACH THE OTHER SIDE OF THE RIVER BEFORE TIME RUNS OUT. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";
var TEXT_DEVELOPED = "DEVELOPED BY";
var TEXT_PRELOADER_CONTINUE = "START";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";